/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Javi
 */
public class Frame extends javax.swing.JFrame {

	/**
	 * Creates new form Frame
	 */
	public Frame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        monHours = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monMins = new javax.swing.JTextField();
        mondayCheckBox = new javax.swing.JCheckBox();
        tuesHours = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tuesMins = new javax.swing.JTextField();
        tuesdayCheckBox = new javax.swing.JCheckBox();
        wedHours = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        wedMins = new javax.swing.JTextField();
        wednesdayCheckBox = new javax.swing.JCheckBox();
        thursHours = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        thursMins = new javax.swing.JTextField();
        thursdayCheckBox = new javax.swing.JCheckBox();
        friHours = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        friMins = new javax.swing.JTextField();
        fridayCheckBox = new javax.swing.JCheckBox();
        satHours = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        satMins = new javax.swing.JTextField();
        saturdayCheckBox = new javax.swing.JCheckBox();
        sunHours = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sunMins = new javax.swing.JTextField();
        sundayCheckBox = new javax.swing.JCheckBox();
        outHours = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        outMinutes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        remaininglHours = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        remaininglMinutes = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        workWeek20 = new javax.swing.JRadioButton();
        workWeek30 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hours Calculator");
        setLocation(new java.awt.Point(760, 390));
        setResizable(false);

        monHours.setText("0");
        monHours.setEnabled(false);
        monHours.setName(""); // NOI18N
        monHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monHoursActionPerformed(evt);
            }
        });

        jLabel1.setText("Hours:");

        jLabel2.setText("Minutes:");

        monMins.setText("0");
        monMins.setEnabled(false);
        monMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monMinsActionPerformed(evt);
            }
        });

        mondayCheckBox.setText("Monday");
        mondayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayCheckBoxActionPerformed(evt);
            }
        });

        tuesHours.setText("0");
        tuesHours.setEnabled(false);
        tuesHours.setName(""); // NOI18N
        tuesHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesHoursActionPerformed(evt);
            }
        });

        jLabel9.setText("Hours:");

        jLabel10.setText("Minutes:");

        tuesMins.setText("0");
        tuesMins.setEnabled(false);
        tuesMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesMinsActionPerformed(evt);
            }
        });

        tuesdayCheckBox.setText("Tuesday");
        tuesdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayCheckBoxActionPerformed(evt);
            }
        });

        wedHours.setText("0");
        wedHours.setEnabled(false);
        wedHours.setName(""); // NOI18N
        wedHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedHoursActionPerformed(evt);
            }
        });

        jLabel11.setText("Hours:");

        jLabel12.setText("Minutes:");

        wedMins.setText("0");
        wedMins.setEnabled(false);
        wedMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedMinsActionPerformed(evt);
            }
        });

        wednesdayCheckBox.setText("Wednesday");
        wednesdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayCheckBoxActionPerformed(evt);
            }
        });

        thursHours.setText("0");
        thursHours.setEnabled(false);
        thursHours.setName(""); // NOI18N
        thursHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursHoursActionPerformed(evt);
            }
        });

        jLabel13.setText("Hours:");

        jLabel14.setText("Minutes:");

        thursMins.setText("0");
        thursMins.setEnabled(false);
        thursMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursMinsActionPerformed(evt);
            }
        });

        thursdayCheckBox.setText("Thursday");
        thursdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayCheckBoxActionPerformed(evt);
            }
        });

        friHours.setText("0");
        friHours.setEnabled(false);
        friHours.setName(""); // NOI18N
        friHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friHoursActionPerformed(evt);
            }
        });

        jLabel15.setText("Hours:");

        jLabel16.setText("Minutes:");

        friMins.setText("0");
        friMins.setEnabled(false);
        friMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friMinsActionPerformed(evt);
            }
        });

        fridayCheckBox.setText("Friday");
        fridayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayCheckBoxActionPerformed(evt);
            }
        });

        satHours.setText("0");
        satHours.setEnabled(false);
        satHours.setName(""); // NOI18N
        satHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satHoursActionPerformed(evt);
            }
        });

        jLabel17.setText("Hours:");

        jLabel18.setText("Minutes:");

        satMins.setText("0");
        satMins.setEnabled(false);
        satMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satMinsActionPerformed(evt);
            }
        });

        saturdayCheckBox.setText("Saturday");
        saturdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayCheckBoxActionPerformed(evt);
            }
        });

        sunHours.setText("0");
        sunHours.setEnabled(false);
        sunHours.setName(""); // NOI18N
        sunHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunHoursActionPerformed(evt);
            }
        });

        jLabel19.setText("Hours:");

        jLabel20.setText("Minutes:");

        sunMins.setText("0");
        sunMins.setEnabled(false);
        sunMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunMinsActionPerformed(evt);
            }
        });

        sundayCheckBox.setText("Sunday");
        sundayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayCheckBoxActionPerformed(evt);
            }
        });

        outHours.setEditable(false);

        jLabel3.setText("Total Hours:");

        outMinutes.setEditable(false);

        jLabel4.setText("Total Minutes");

        jLabel5.setText("Remaining Hours:");

        remaininglHours.setEditable(false);

        jLabel6.setText("Remaining Minutes");

        remaininglMinutes.setEditable(false);

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        jLabel8.setText("Check the days worked then input hours and minutes worked that day.  Click calculate to view total hours/total minutes and remaining hours/remaing minutes.");

        buttonGroup1.add(workWeek20);
        workWeek20.setText("20 Hour Work Week");
        workWeek20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workWeek20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(workWeek30);
        workWeek30.setText("30 Hour Work Week");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(workWeek20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workWeek30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mondayCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuesdayCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tuesHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tuesMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wednesdayCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(wedMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thursdayCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(thursHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(thursMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fridayCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(friHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(friMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saturdayCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(satHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(satMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sundayCheckBox)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sunHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(sunMins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel20))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculate)
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(outHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(outMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(remaininglHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(remaininglMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))))))
                    .addComponent(jLabel7))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workWeek20)
                    .addComponent(workWeek30))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mondayCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fridayCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(friHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(friMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(thursdayCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(thursHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thursMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wednesdayCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(wedHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wedMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tuesdayCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tuesHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tuesMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saturdayCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(satHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(satMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sundayCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sunHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sunMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calculate)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(outHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(remaininglMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(remaininglHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monHoursActionPerformed

    private void monMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monMinsActionPerformed

    private void mondayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayCheckBoxActionPerformed
        if(mondayCheckBox.isSelected()){
            monHours.setEnabled(true);
            monMins.setEnabled(true);
        }
        else if(!mondayCheckBox.isSelected()){
            monHours.setEnabled(false);
            monMins.setEnabled(false);
        }
    }//GEN-LAST:event_mondayCheckBoxActionPerformed

    private void tuesHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesHoursActionPerformed
        
    }//GEN-LAST:event_tuesHoursActionPerformed

    private void tuesMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesMinsActionPerformed

    private void tuesdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayCheckBoxActionPerformed
        if(tuesdayCheckBox.isSelected()){
            tuesHours.setEnabled(true);
            tuesMins.setEnabled(true);
        }
        else if(!tuesdayCheckBox.isSelected()){
            tuesHours.setEnabled(false);
            tuesMins.setEnabled(false);
        }
    }//GEN-LAST:event_tuesdayCheckBoxActionPerformed

    private void wedHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wedHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wedHoursActionPerformed

    private void wedMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wedMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wedMinsActionPerformed

    private void wednesdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayCheckBoxActionPerformed
        if(wednesdayCheckBox.isSelected()){
            wedHours.setEnabled(true);
            wedMins.setEnabled(true);
        }
        else if(!wednesdayCheckBox.isSelected()){
            wedHours.setEnabled(false);
            wedMins.setEnabled(false);
        }
    }//GEN-LAST:event_wednesdayCheckBoxActionPerformed

    private void thursHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursHoursActionPerformed

    private void thursMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursMinsActionPerformed

    private void thursdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayCheckBoxActionPerformed
        if(thursdayCheckBox.isSelected()){
            thursHours.setEnabled(true);
            thursMins.setEnabled(true);
        }
        else if(!thursdayCheckBox.isSelected()){
            thursHours.setEnabled(false);
            thursMins.setEnabled(false);
        }
    }//GEN-LAST:event_thursdayCheckBoxActionPerformed

    private void friHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friHoursActionPerformed

    private void friMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friMinsActionPerformed

    private void fridayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayCheckBoxActionPerformed
        if(fridayCheckBox.isSelected()){
            friHours.setEnabled(true);
            friMins.setEnabled(true);
        }
        else if(!fridayCheckBox.isSelected()){
            friHours.setEnabled(false);
            friMins.setEnabled(false);
        }
    }//GEN-LAST:event_fridayCheckBoxActionPerformed

    private void satHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satHoursActionPerformed

    private void satMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satMinsActionPerformed

    private void saturdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayCheckBoxActionPerformed
        if(saturdayCheckBox.isSelected()){
            satHours.setEnabled(true);
            satMins.setEnabled(true);
        }
        else if(!saturdayCheckBox.isSelected()){
            satHours.setEnabled(false);
            satMins.setEnabled(false);
        }
    }//GEN-LAST:event_saturdayCheckBoxActionPerformed

    private void sunHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunHoursActionPerformed

    private void sunMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunMinsActionPerformed

    private void sundayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayCheckBoxActionPerformed
        if(sundayCheckBox.isSelected()){
            sunHours.setEnabled(true);
            sunMins.setEnabled(true);
        }
        else if(!sundayCheckBox.isSelected()){
            sunHours.setEnabled(false);
            sunMins.setEnabled(false);
        }
    }//GEN-LAST:event_sundayCheckBoxActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        int totalHours = 0;
        int totalMinutes = 0;
        if(mondayCheckBox.isSelected()){
            totalHours += Integer.parseInt(monHours.getText());
            totalMinutes += Integer.parseInt(monMins.getText());
            
        }
        if(tuesdayCheckBox.isSelected()){
            totalHours += Integer.parseInt(tuesHours.getText());
            totalMinutes += Integer.parseInt(tuesMins.getText());
        }
        if(wednesdayCheckBox.isSelected()){
            totalHours += Integer.parseInt(wedHours.getText());
            totalMinutes += Integer.parseInt(wedMins.getText());
        }
        if(thursdayCheckBox.isSelected()){
            totalHours += Integer.parseInt(thursHours.getText());
            totalMinutes += Integer.parseInt(thursMins.getText());
        }
        if(fridayCheckBox.isSelected()){
            totalHours += Integer.parseInt(friHours.getText());
            totalMinutes += Integer.parseInt(friMins.getText());
        }
        if(saturdayCheckBox.isSelected()){
            totalHours += Integer.parseInt(satHours.getText());
            totalMinutes += Integer.parseInt(satMins.getText());
        }
        if(sundayCheckBox.isSelected()){
            totalHours += Integer.parseInt(sunHours.getText());
            totalMinutes += Integer.parseInt(sunMins.getText());
        }
        
        totalHours += hourcounter.HourCounter.convertMinutesToHours(totalMinutes);
        totalMinutes = hourcounter.HourCounter.getRemainderMinutes(totalMinutes);
        outHours.setText("" + totalHours);
        outMinutes.setText("" + totalMinutes);
        System.out.println(totalHours);
        System.out.println(totalMinutes);
    }//GEN-LAST:event_calculateActionPerformed

    private void workWeek20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workWeek20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workWeek20ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField friHours;
    private javax.swing.JTextField friMins;
    private javax.swing.JCheckBox fridayCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField monHours;
    private javax.swing.JTextField monMins;
    private javax.swing.JCheckBox mondayCheckBox;
    private javax.swing.JTextField outHours;
    private javax.swing.JTextField outMinutes;
    private javax.swing.JTextField remaininglHours;
    private javax.swing.JTextField remaininglMinutes;
    private javax.swing.JTextField satHours;
    private javax.swing.JTextField satMins;
    private javax.swing.JCheckBox saturdayCheckBox;
    private javax.swing.JTextField sunHours;
    private javax.swing.JTextField sunMins;
    private javax.swing.JCheckBox sundayCheckBox;
    private javax.swing.JTextField thursHours;
    private javax.swing.JTextField thursMins;
    private javax.swing.JCheckBox thursdayCheckBox;
    private javax.swing.JTextField tuesHours;
    private javax.swing.JTextField tuesMins;
    private javax.swing.JCheckBox tuesdayCheckBox;
    private javax.swing.JTextField wedHours;
    private javax.swing.JTextField wedMins;
    private javax.swing.JCheckBox wednesdayCheckBox;
    private javax.swing.JRadioButton workWeek20;
    private javax.swing.JRadioButton workWeek30;
    // End of variables declaration//GEN-END:variables
}
